### ISSUE TITLE
[BETA] Episodes title problem on tvdb4 possibly + #193 not solved

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#195]
To not hijack my other issue that's already fixed now, after the last update (probably later too, didn't noticed) some of the episode names on One Piece using tvdb4 are missing, and in their place they have a random date starting with 1970.

https://i.imgur.com/E1ORKhg.jpg

Logs below:
[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1994650/logs.zip)

I just found out that #193 isn't solved yet. I found out the following folders inside com.plexapp.agents.hama/DataItems:

- TheTVDBfanart
- TheTVDBseasons
- TheTVDBposters

**Comment by sven-7** [comment]
My One Piece in tvdb4 does not seem to have reacted the same way.

<img width="1155" alt="screen shot 2018-05-11 at 11 33 03 am" src="https://user-images.githubusercontent.com/18091557/39917881-26a23676-550f-11e8-961e-ff02a40245db.png">

**Comment by KurtzPT** [comment]
I just tested it in a cleaner way, created a new library and added only one piece tvdb4, started the scan.

Most episodes names are missing, with the generic Episode X name in it. I can't find any 1970 date on the names this time.

Logs were cleared before this test, here are the new logs:

[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1994827/logs.zip)

**Comment by ZeroQI** [comment]
i did solve the folder issue but the folders wrongly created are staying so they have to be moved back manually inside TheTVDB and should not be re-created again. if they are let me know
- TheTVDB 'fanart'
- TheTVDB 'seasons'
- TheTVDB 'posters'

Scanner logs and force id all good, naming is good as well so agent issue
Issue started at episode 539

```
airedSeason: 15, airedEpisodeNumber: 23
json: {
'seriesId': 81797, 
'airsAfterSeason': None, 
'dvdEpisodeNumber': 23, 
'productionCode': u'', 
'overview': "[...]",
'airedSeasonID': 475545, 
'thumbAdded': u'', 
'episodeName': 'Revived Relations, Nami and the Fishman Pirates', 
'airedSeason': 15, 
'airsBeforeSeason': None, 
'showUrl': u'', 
'id': 4278474, 
'dvdDiscid': u'', 
'filename': 'episodes/81797/4278474.jpg', 
'dvdSeason': 15, 
'writers': [], 
'airedEpisodeNumber': 23, 
'absoluteNumber': 539, 
'thumbHeight': '225', 
'imdbId': u'', 
'lastUpdated': 1445214432, 
'director': u'', 
'lastUpdatedBy': 410201, 
'dvdChapter': None, 
'airsBeforeEpisode': None, 
'language': {'overview': 'en', 'episodeName': 'en'}, 
'thumbAuthor': 360250, 
'siteRatingCount': 4, 
'directors': [], 
'firstAired': '2012-03-18', 
'guestStars': [], 
'siteRating': 7.8, 
'thumbWidth': '400'
}
```
it is like there is an issue with the multitasking, there is no info
will have to cleanup logging, and put the mapped season and episode and title displayed in logs for such occurrences troubleshooting

**Comment by KurtzPT** [comment]
I've tried to refresh metadata more than one time and it seems to be missing names all those times I tried... so either it's a concurrency problem or something else.

Those folders were created after I updated hama, I did clean every extra folder before updating.

**Comment by ZeroQI** [comment]
I thought you made a typo, apologies. yeah forgot a forward slash... Pushed the update now

**Comment by KurtzPT** [comment]
That fixed the folder issue. I'll wait for new updates on the one piece problem to retest it.

**Comment by ZeroQI** [comment]
Could you attach the filelist? really don't want to create 700+ eps by hand and you might want me to have the same conditions as you. I wrote a script to recreate dummy fiels from filelists...

**Comment by ZeroQI** [comment]
When you say it wasn'r recognised, it was not showing at all (scanner issue), or no title and/or no screenshot?
reproduced title edep 157 missing. 
uploaded new version with multithread disabled. Please test and report.

**Comment by KurtzPT** [comment]
It's not a scanner problem since the episodes appear, they just miss their titles and probably missing the pictures too from tvdb.

**Comment by ZeroQI** [comment]
i did update my github folder but seem like i didn't synched it to gihub after editing text
Will do towards 12 uk itme

**Comment by KurtzPT** [comment]
I'll probably just be able to test it at night time in UK or just tomorrow.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/commit/42fc9ab7c529606eff47abfa015096e715c7f1e7 it was uploaded but something weird synched up afterwards giving illusion i updated the readme...

**Comment by ZeroQI** [comment]
Please test and report, logging simplified and improved, handling anidb endings correctly now

**Comment by sven-7** [comment]
I'm not having my One Piece (tvdb4) showing up with an series title of "One Piece Movie 13".  

<img width="1250" alt="screen shot 2018-05-14 at 8 33 26 am" src="https://user-images.githubusercontent.com/18091557/39997601-7e22513a-5751-11e8-9bf5-6139fc65c852.png">


[One Piece.agent-update.zip](https://github.com/ZeroQI/Hama.bundle/files/2000645/One.Piece.agent-update.zip)

**Comment by KurtzPT** [comment]
So I updated to last version and the problem still is present, most episodes don't have the title name. I didn't have the problem above of sven-7.

Logs below.
[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2000977/logs.zip)

**Comment by sven-7** [comment]
One Piece went back to being just One Piece for me. No idea what happened to it.

**Comment by ZeroQI** [comment]
@sven-7 Sorry but i don't get what you mean, tried one piece tvdb4 on few eps only and looks good for me
@KurtzPT since i have the filelist now i reproduced your library. logs provided show all ok until s06e119 and no logs anymore. reproduced the issue

**Comment by ZeroQI** [comment]
Am re-writing the TVDB numbering part, very obscure, should be simpler and faster at the end but takes time... Will keep you posted

**Comment by ZeroQI** [comment]
Please test and report

**Comment by KurtzPT** [comment]
It fixed the One Piece problem here.

**Comment by vultureman** [comment]
Mine's fixed as well ZeroQI, althought i got it fixed yesterday by removing my seasons, leaving the folder named "One Piece [anidb-69]" and using the default names of the files as they download (just episode number, no season number) and now they're getting the proper episode titles. Less for me to rename, and I can live without the seasons.

**Comment by ZeroQI** [comment]
@vultureman so when you had seasons the folder was also named 'One Piece [anidb-69]' ? Working on anidb loading in absolute mode ATM to fix remaining issues

**Comment by KurtzPT** [comment]
Closing it, since it's fixed on my end.

**Comment by ZeroQI** [comment]
tested anidb3 and worked for bleach/one piece.
anyhow should hve worked, if not working on latest code open a git bug and will solve it
