### ISSUE TITLE
No poster with Anidb

### ISSUE THREAD

**Issue by rosystain** [ZeroQI/Hama.bundle#308]
Few days ago I met a problem about match issue just like [#305](https://github.com/ZeroQI/Hama.bundle/issues/305).

After deleting anidb-title.xml and updating the agent, it fixed but not adding poster.

So I delete the HAMA Cache and create a new Library for a fresh scan.

<img width="995" alt="Snipaste_2019-05-05_12-24-51" src="https://user-images.githubusercontent.com/27495128/57188451-6fb93480-6f31-11e9-9ddc-92e6bd76adad.png">

The metadata seems fine but just no poster.

<img width="1205" alt="Snipaste_2019-05-05_12-36-25" src="https://user-images.githubusercontent.com/27495128/57188501-6b414b80-6f32-11e9-8d10-f4e9a652b587.png">

I checked the log but there was no 'banned message' shown.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3145141/com.plexapp.agents.hama.log)

**Comment by EndOfLine369** [comment]
Pull fresh from HAMA master. 
I had same issue. Should now be fixed in https://github.com/ZeroQI/Hama.bundle/commit/1ce898cfc5e90665a2274eaa32b744914d5876fc
Second thing AniDB seems to have changed without notice.

**Comment by rosystain** [comment]
> Pull fresh from HAMA master.
> I had same issue. Should now be fixed in [1ce898c](https://github.com/ZeroQI/Hama.bundle/commit/1ce898cfc5e90665a2274eaa32b744914d5876fc)
> Second thing AniDB seems to have changed without notice.

It works! Thank you

**Comment by DarthKnight12** [comment]
how do i clear the caches ?

**Comment by ZeroQI** [comment]
go to your Plex folder, then "Plug-In Support/Data/com.plexapp.agents.hama/DataItems/AniDB" and delete title xml

**Comment by DarthKnight12** [comment]
dont know what it is but ive done everything thats has been said already, but some shows still dont want to match and pull the metadata

**Comment by ZeroQI** [comment]
You reply to a closed bug report about "no posters from anyDB" with a show not matching issue (so different issue) and get surprised the recommended solution doesn't work???
You didn't attach agent logs like the first person, and as listed in the readme's troubleshooting steps...

**Comment by DarthKnight12** [comment]
Sorry Zero, i wasnt complaining, ive had a look at the other threads aswell (which are also closed), and i figured this was a scanner related issue, but yes posters and metadata doesnt match and for some reason also the actual shows wont match aswell. ill let plex do its thing a little longer (maybe itll match) and if it doesnt ill open up a new issue including logs and all ok ? sorry for the confusion

**Comment by ZeroQI** [comment]
If files go in Plex scanner is fine.
If search doesn't work the agent crash and need logs.  Seem to me the anidb title XML bug but if you run latest hama and deleted it manually should be an unrelated issue.
Please open new vug report attaching logs
